package com.example.habittracker.network_api.di.mediators

import com.example.habittracker.network_api.di.providers.NetworkComponentProvider

interface NetworkFacadeComponentProviders : NetworkComponentProvider