package com.example.habittracker.viewmodels_api.di.mediators

import com.example.habittracker.viewmodels_api.di.providers.ViewModelsComponentProvider

interface ViewModelsFacadeComponentProviders : ViewModelsComponentProvider